-- AlterTable
ALTER TABLE "Graph" ALTER COLUMN "graphValue_x" DROP NOT NULL,
ALTER COLUMN "graphValue_y" DROP NOT NULL,
ALTER COLUMN "dataCircle" DROP NOT NULL,
ALTER COLUMN "dataScatter" DROP NOT NULL,
ALTER COLUMN "dataRadar" DROP NOT NULL,
ALTER COLUMN "graphType" DROP NOT NULL;
